"""Initial migration

Revision ID: 75924f3dff5e
Revises: 
Create Date: 2024-05-27 01:32:07.548445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75924f3dff5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', sa.String()))
    op.drop_column('customer', 'citizen_id')
    op.create_foreign_key(None, 'employee', 'manager', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'hotel', 'manager', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'booking', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'customer', ['customer_id'], ['id'])
    op.drop_column('payment', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.add_column('customer', sa.Column('citizen_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###
